const equipmentsTypes = {
    ADD_NEW_EQUIPMENT_START: 'ADD_NEW_EQUIPMENT_START',
    FETCH_EQUIPMENTS_START: 'FETCH_EQUIPMENTS_START',
    SET_EQUIPMENTS: 'SET_EQUIPMENTS',
    DELETE_EQUIPMENT_START: 'DELETE_EQUIPMENT_START',
    EDIT_EQUIPMENT_START: 'EDIT_EQUIPMENT_START',
    FETCH_EQUIPMENT_START: 'FETCH_EQUIPMENT_START',
    SET_EQUIPMENT: 'SET_EQUIPMENT',
};

export default equipmentsTypes;