const workshopsTypes = {
    ADD_NEW_WORKSHOP_START: 'ADD_NEW_WORKSHOP_START',
    FETCH_WORKSHOPS_START: 'FETCH_WORKSHOPS_START',
    SET_WORKSHOPS: 'SET_WORKSHOPS',
    DELETE_WORKSHOP_START: 'DELETE_WORKSHOP_START',
    EDIT_WORKSHOP_START: 'EDIT_WORKSHOP_START',
    FETCH_WORKSHOP_START: 'FETCH_WORKSHOP_START',
    SET_WORKSHOP: 'SET_WORKSHOP',
};

export default workshopsTypes;