const spacesTypes = {
    ADD_NEW_SPACE_START: 'ADD_NEW_SPACE_START',
    FETCH_SPACES_START: 'FETCH_SPACES_START',
    SET_SPACES: 'SET_SPACES',
    DELETE_SPACE_START: 'DELETE_SPACE_START',
    EDIT_SPACE_START: 'EDIT_SPACE_START',
    FETCH_SPACE_START: 'FETCH_SPACE_START',
    SET_SPACE: 'SET_SPACE',
};

export default spacesTypes;